# Site settings
title: Kenji Hiraoka
description: A blog about Kenji Hiraoka
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Willian Kenji Hiraoka
user_description: I'm a brazilian guy looking for big challenges and improve my knowledge. Nowadays, I'm a Data Engineer at QuintoAndar and a begginer pianist!
user_expertise: I already have 2 years of experience at Data area and during this time I have worked at Beblue and QuintoAndar. I work with Python, Docker, Git, AWS, Apache Airflow, Metabase, Kubernetes.
user_title: Data Engineer
email: willian22kenji@gmail.com
twitter_username: kenjihiraoka
github_username:  kenjihiraoka

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
